# Model
device: 1

alg_name: "FT"
name: huggingface_cache/opt-6.7b
model_name: blip2
model_class: Blip2OPT
tokenizer_class: GPT2Tokenizer
tokenizer_name: huggingface_cache/opt-6.7b
inner_params:
- Qformer

# Method
alg: ft
num_steps: 10
lr: 1e-6
edit_lr: 2e-4
lr_lr: 1e-4
lr_scale: 1.0
weight_decay: 0
seed: 42
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null
one_sided: False
n_hidden: 1
hidden_dim: null
init: id
norm: True
combine: True
x_only: False
delta_only: False
act: relu
rank: 1920
mlp_class: IDMLP
shared: True
archive: null

# Train
batch_size: 1
model_save_pt: 1000
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 100
eval_log_interval: 1000
final_eval: True
val_interval: 5000
early_stop_patience: 6000
early_stop_key: "loss/total_edit_val"
eval_only: True
half: False
debug: False
save: False
verbose: True

val_batch_size: 1
accumulate_bs: 2
val_steps: 500 # only for debug
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results/ft_vis

# Multimodal
qformer_checkpoint: huggingface_cache/blip2_pretrained_opt6.7b.pth
qformer_name_or_path: huggingface_cache/bert-base-uncased
state_dict_file: huggingface_cache/eva_vit_g.pth
# image
image: data/CLEVR_CoGenT_v1.0/images