# Model
device: 0

name: huggingface_cache/opt-6.7b
model_name: blip2
model_class: Blip2OPT
small_name: huggingface_cache/opt-1.3b
tokenizer_class: GPT2Tokenizer
tokenizer_name: huggingface_cache/opt-6.7b
cls_name: huggingface_cache/distilbert-base-cased
cls_class: AutoModel 
inner_params:
- opt_model.model.decoder.layers.29.fc1.weight
- opt_model.model.decoder.layers.29.fc2.weight
- opt_model.model.decoder.layers.30.fc1.weight
- opt_model.model.decoder.layers.30.fc2.weight
- opt_model.model.decoder.layers.31.fc1.weight
- opt_model.model.decoder.layers.31.fc2.weight

# Method
alg: SERAC_MULTI
lr: 1e-5
edit_lr: 1e-3
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: null

batch_size: 1
model_save_pt: 2000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 10
val_interval: 100
early_stop_patience: 50000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 500
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: huggingface_cache/blip2_pretrained_opt6.7b.pth
qformer_name_or_path: huggingface_cache/bert-base-uncased
state_dict_file: huggingface_cache/eva_vit_g.pth

# image
image: data/CLEVR_CoGenT_v1.0/images