# config.yaml

# Model related parameters
model_name: "qwenvl"
model_path: "/root/autodl-tmp/mllm_ke/AKE-main/huggingface_cache/Qwen2.5-VL"
device: "cuda"

# Data related parameters
img_root: "/root/autodl-tmp/mllm_ke/AKE-main/data/CLEVR_CoGenT_v1.0/images"
img_root_modified: "/root/autodl-tmp/mllm_ke/akedit/dataset/images_modified/qwenvl"
img_masks: "/root/autodl-tmp/mllm_ke/akedit/dataset/images_masks/qwenvl"
image_size: 448
patch_num: 729

dataset_path: "/root/autodl-tmp/mllm_ke/AKE-main/data/qwenvl_new/val1_dataset.json"
image_direction_dataset_dir: "/root/autodl-tmp/mllm_ke/akedit/dataset/CLEVR_CoGenT_v1.0/images/loc_data"

# Training related parameters
lr: 0.0001
epochs: 10
weight_decay: 0.01
max_length: 512

# Editing method parameters
edit_layers: 15

# Path parameters
output_dir: "/root/autodl-tmp/mllm_ke/akedit/results"
cache_dir: "./cache"
log_dir: "./logs"

# Other parameters
seed: 42
debug: false
resume: null